import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'

const style = {
  wrapper: 'flex justify-center h-screen w-screen select-none bg-[#15202b] text-white',
  content: 'max-w-[1400px] w-2/3 flex justify-between'
}


export default function Home() {
  return (
    <div className={style.wrapper}>
      <Head>
        <title>Web3 Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div className={style.content}>

    {/* Sidebar */}
    <Sidebar />
    {/* Feed */}
    <Feed />
    {/* Widgets */}
    <h1>Widgets</h1>
</div>

    </div>
  )
}
